export const PREORDER_ADD_ITEM = 'PREORDER_ADD_ITEM'
export const PREORDER_REMOVE_ITEM = 'PREORDER_REMOVE_ITEM'
export const PREORDER_RESET = 'PREORDER_RESET'

export const PREORDER_CREATE_REQUEST = 'PREORDER_CREATE_REQUEST'
export const PREORDER_CREATE_SUCCESS = 'PREORDER_CREATE_SUCCESS'
export const PREORDER_CREATE_FAIL = 'PREORDER_CREATE_FAIL'
